apiVersion: v1
kind: Service
metadata:
  name: web3-security-kafka
spec:
  selector:
    app: web3-security-kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web3-security-kafka
spec:
  serviceName: web3-security-kafka
  replicas: 1
  selector:
    matchLabels:
      app: web3-security-kafka
  template:
    metadata:
      labels:
        app: web3-security-kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.7
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@web3-security-kafka-0.web3-security-kafka:9093"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://web3-security-kafka:9092
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
